import { defineConfig } from "astro/config";
import cloudflare from "@astrojs/cloudflare";
import react from "@astrojs/react";
import tailwindcss from "@tailwindcss/vite";

// `astro.config.mjs` runs as a plain Node script per-invocation (not through
// Vite), so `process.argv[2]` is a reliable, side-effect-free way to tell
// `astro dev` apart from `astro build`/`astro preview` — unlike
// `defineConfig`'s function form (`({ command }) => ({...})`), which is NOT
// used here on purpose: passing a function (even one whose body never runs)
// somehow broke `@tailwindcss/vite`'s resolution of `@import "tailwindcss"`
// from `packages/ui/src/tokens` in dev mode (found investigating the
// `run_worker_first`/dev-mode issue below) for reasons not otherwise
// root-caused — a plain object plus this check avoids the whole class of
// problem.
const isDevCommand = process.argv[2] === "dev";

// See ADR-0001: one Astro app, deployed as one Cloudflare Worker, with a
// custom worker entry (src/worker.ts) so the same deployable also exports a
// scheduled() handler for monitoring cron (Part 4).
export default defineConfig({
  site: process.env.PUBLIC_SITE_URL ?? "https://crawlpact.com",
  output: "server",
  adapter: cloudflare({
    imageService: "compile",
    platformProxy: { enabled: true },
    // `wrangler.jsonc`'s production `assets.run_worker_first: ["/*", ...]`
    // (Phase 2 of the app-subdomain migration, ADR-0010) is a real,
    // deliberate production behavior change: it makes `src/worker.ts` run
    // in front of the ASSETS binding for every document path, not just SSR
    // ones, closing a gap in the app-host boundary check. In a real
    // deployed Worker that's the only thing "/*" can match. In `astro dev`,
    // the same top-level config is read by `@cloudflare/vite-plugin`'s own
    // dev-mode static-routing simulation, which then ALSO matches Vite's
    // internal dev-only requests (`/@vite/client`, `/@react-refresh`,
    // component modules served from their raw absolute filesystem path,
    // etc.) — those aren't real, listable assets, so they can't be named in
    // an exclusion glob the way `!/_astro/*` can, and routing them into
    // `src/worker.ts`'s fetch handler 404s them, which silently breaks
    // every `client:load`/`client:idle` island's hydration (found via PR
    // #171's real CI: `setup-customer.setup.ts`'s "Create account" click
    // never revealed the Display name field).
    //
    // A `config` customizer function (the documented way to post-process
    // the resolved Wrangler config) can't fix this: `@astrojs/cloudflare`
    // already claims that exact option internally for its own session/image
    // binding wiring and unconditionally overwrites whatever `config` this
    // file passes in (`cfPluginConfig = { ...cloudflareOptions,
    // ...adapterPluginConfig }` in its own source — `adapterPluginConfig`
    // always wins). `configPath` is the one config-selection lever the
    // adapter does NOT reserve for itself, so `apps/web/wrangler.dev.jsonc`
    // (generated by `scripts/generate-dev-wrangler-config.mjs`, run
    // automatically by this package's `dev` script — byte-derived from the
    // real `wrangler.jsonc` with only `assets.run_worker_first` stripped, so
    // it cannot drift) is used instead, for the `astro dev` command only.
    // `astro build` (and therefore `dist/server/wrangler.json`, the config
    // `scripts/deploy.sh` actually deploys) always reads the real
    // `apps/web/wrangler.jsonc`, so production behavior is byte-for-byte
    // unchanged.
    ...(isDevCommand ? { configPath: "./wrangler.dev.jsonc" } : {}),
  }),
  integrations: [react()],
  vite: {
    plugins: [tailwindcss()],
  },
});
