/**
 * Stable error codes returned by the CrawlPact API. This is the single
 * source of truth referenced by docs/api/ERROR_CATALOGUE.md — keep both in
 * sync when adding a code.
 */
export const ERROR_CODES = [
  "VALIDATION_FAILED",
  "NOT_FOUND",
  "UNAUTHENTICATED",
  "FORBIDDEN",
  "RATE_LIMITED",
  "INTERNAL_ERROR",
  "SERVICE_UNAVAILABLE",

  "AUDIT_TARGET_INVALID",
  "AUDIT_TARGET_UNSAFE",
  "AUDIT_ENGINE_DISABLED",
  "AUDIT_NOT_FOUND",
  "AUDIT_QUOTA_EXCEEDED",
  "AUDIT_CONTINUATION_INVALID",
  "SCAN_ALREADY_RUNNING",

  "AUTH_CHALLENGE_EXPIRED",
  "AUTH_CREDENTIAL_INVALID",
  "AUTH_RECOVERY_CODE_INVALID",
  "AUTH_SESSION_EXPIRED",
  "AUTH_STEP_UP_REQUIRED",

  "DOMAIN_LIMIT_REACHED",
  "DOMAIN_DUPLICATE",
  "GROUP_NOT_EMPTY",

  "BILLING_WEBHOOK_SIGNATURE_INVALID",
  "BILLING_WEBHOOK_REPLAYED",
  "BILLING_SYNC_ERROR",

  "SHARE_TOKEN_INVALID",

  "ADMIN_REASON_REQUIRED",
  "ADMIN_ACTION_FORBIDDEN",

  "MAINTENANCE_MODE_ACTIVE",
] as const;

export type ErrorCode = (typeof ERROR_CODES)[number];

export const ERROR_HTTP_STATUS: Record<ErrorCode, number> = {
  VALIDATION_FAILED: 400,
  NOT_FOUND: 404,
  UNAUTHENTICATED: 401,
  FORBIDDEN: 403,
  RATE_LIMITED: 429,
  INTERNAL_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,

  AUDIT_TARGET_INVALID: 400,
  AUDIT_TARGET_UNSAFE: 400,
  AUDIT_ENGINE_DISABLED: 503,
  AUDIT_NOT_FOUND: 404,
  AUDIT_QUOTA_EXCEEDED: 429,
  AUDIT_CONTINUATION_INVALID: 410,
  SCAN_ALREADY_RUNNING: 409,

  AUTH_CHALLENGE_EXPIRED: 400,
  AUTH_CREDENTIAL_INVALID: 400,
  AUTH_RECOVERY_CODE_INVALID: 400,
  AUTH_SESSION_EXPIRED: 401,
  AUTH_STEP_UP_REQUIRED: 401,

  DOMAIN_LIMIT_REACHED: 403,
  DOMAIN_DUPLICATE: 409,
  GROUP_NOT_EMPTY: 409,

  BILLING_WEBHOOK_SIGNATURE_INVALID: 400,
  BILLING_WEBHOOK_REPLAYED: 200,
  BILLING_SYNC_ERROR: 409,

  SHARE_TOKEN_INVALID: 404,

  ADMIN_REASON_REQUIRED: 400,
  ADMIN_ACTION_FORBIDDEN: 403,

  MAINTENANCE_MODE_ACTIVE: 503,
};

export class ApiError extends Error {
  constructor(
    readonly code: ErrorCode,
    message: string,
    readonly details?: Record<string, unknown>,
  ) {
    super(message);
    this.name = "ApiError";
  }

  get httpStatus(): number {
    return ERROR_HTTP_STATUS[this.code];
  }
}
