#!/usr/bin/env bash
# Reproduces every mandatory GitHub merge check locally, as closely as
# practical, before pushing. Never contacts production/preview D1/KV, never
# uses a Paddle Live credential, never deploys a Worker. Exits non-zero on
# any failure and cleans up its own temporary files either way.
#
# Usage: pnpm verify:push
set -euo pipefail
cd "$(dirname "$0")/.."

BUILT_DEV_VARS_PATH="apps/web/dist/server/.dev.vars"
SERVER_PID=""

cleanup() {
  if [[ -n "$SERVER_PID" ]] && kill -0 "$SERVER_PID" 2>/dev/null; then
    kill "$SERVER_PID" 2>/dev/null || true
    wait "$SERVER_PID" 2>/dev/null || true
  fi
  # wrangler dev daemonizes its own child processes, so $SERVER_PID may not
  # be the real long-lived process — fall back to freeing the port directly.
  lsof -ti:4321 2>/dev/null | xargs -r kill -9 2>/dev/null || true
  # apps/web/dist is a build output directory (gitignored, never a file the
  # developer authored), so this one is safe to remove outright — unlike
  # apps/web/.dev.vars (the developer's own real local-dev secrets file),
  # this script never writes there.
  rm -f "$BUILT_DEV_VARS_PATH"
}
trap cleanup EXIT

echo "==> Checking Node/pnpm versions"
node_version="$(node --version)"
pnpm_version="$(pnpm --version)"
if [[ "$node_version" != v22.12.* && "$node_version" != v22.1[3-9].* && "$node_version" != v22.2*.* ]]; then
  echo "verify:push: expected Node 22.12.x, found $node_version — continuing, but CI pins 22.12.0." >&2
fi
echo "    node $node_version / pnpm $pnpm_version"

echo "==> Confirming no real production/Live credential is present in this shell"
for var in CLOUDFLARE_API_TOKEN CLOUDFLARE_ACCOUNT_ID PADDLE_API_KEY PADDLE_WEBHOOK_SECRET; do
  if [[ -n "${!var:-}" ]]; then
    echo "verify:push: refusing — \$$var is set in this shell. Unset it before running verify:push (this command must never be able to reach a real Cloudflare/Paddle account)." >&2
    exit 1
  fi
done

echo "==> Preparing a disposable local D1 database"
pnpm run db:migrate
pnpm run db:seed || echo "    (seed:local reported an error — usually just already-seeded data from a prior local run; continuing)"

echo "==> Format check"
pnpm run format:check

echo "==> Lint"
pnpm run lint

echo "==> Type check"
pnpm run typecheck

echo "==> Unit tests"
pnpm run test:unit

echo "==> Integration tests"
pnpm run test:integration

echo "==> Validate D1 migrations against Drizzle schema"
pnpm run db:validate

echo "==> Production build"
pnpm run build

echo "==> Writing temporary CI-local .dev.vars for the built Worker (removed on exit)"
# wrangler dev --local resolves .dev.vars relative to its own config file's
# directory (apps/web/dist/server/wrangler.json, generated by the build
# above — not apps/web/wrangler.jsonc), confirmed via wrangler's own source.
# See docs/status/KNOWN_RISKS.md.
cat > "$BUILT_DEV_VARS_PATH" << 'DEVVARS'
PUBLIC_APP_ENV=local
PUBLIC_SITE_URL=http://localhost:4321
SESSION_SIGNING_SECRET=ci-placeholder-secret-value-not-real-00000000
WEBAUTHN_RP_ID=localhost
WEBAUTHN_RP_ORIGIN=http://localhost:4321
PADDLE_API_KEY=ci-placeholder
PADDLE_ENVIRONMENT=sandbox
PADDLE_WEBHOOK_SECRET=ci-placeholder
PADDLE_PRICE_ID_SOLO=pri_ci_placeholder
PADDLE_PRICE_ID_PRO=pri_ci_placeholder
PADDLE_PRICE_ID_AGENCY=pri_ci_placeholder
PUBLIC_PADDLE_CLIENT_TOKEN=ci-placeholder
BILLING_ENABLED=false
AUDIT_ENGINE_ENABLED=true
DEVVARS

echo "==> Starting the built Worker (wrangler dev --local)"
# Real, production-like built-server E2E — not Astro dev mode. A prior
# attempt at this reproducibly crashed wrangler dev --local in real CI
# (Miniflare's own D1 connection broke once tests/e2e/helpers/admin-db.ts
# wrote via a *separate* `wrangler d1 execute --local` process concurrently)
# — see docs/status/KNOWN_RISKS.md's "Built-server E2E reverted..." entry.
# Fixed by routing admin-db.ts's writes through this same running server
# instead, via the env-gated apps/web/src/pages/api/test-only routes — no
# second process ever touches the local D1 sqlite file now. --persist-to
# points at the same state directory pnpm db:migrate/db:seed already wrote
# via apps/web/wrangler.jsonc (both configs share the same D1
# database_name/binding). Matches ci.yml's browser-smoke job exactly, so
# this script keeps meaning what it claims to mean: a local reproduction of
# the real required CI gate.
X_LOCAL_EXPLORER=false pnpm exec wrangler dev \
  --local \
  --config apps/web/dist/server/wrangler.json \
  --persist-to apps/web/.wrangler/state \
  --port 4321 > /tmp/verify-push-server.log 2>&1 &
SERVER_PID=$!

if ! npx wait-on http://localhost:4321 --timeout 60000; then
  echo "verify:push: the local server never came up — see /tmp/verify-push-server.log" >&2
  cat /tmp/verify-push-server.log >&2 || true
  exit 1
fi

echo "==> Required Chromium E2E smoke"
CI=true PLAYWRIGHT_BASE_URL=http://localhost:4321 pnpm run test:e2e:chromium

echo "==> Required Chromium accessibility smoke"
CI=true PLAYWRIGHT_BASE_URL=http://localhost:4321 pnpm run test:a11y:chromium

echo "==> Secret scan"
pnpm run secrets:scan

echo
echo "verify:push: all checks passed."
